### ISSUE TITLE
currentUser not accessible in Tapglue.swift

### ISSUE THREAD

**Issue by hellozimi** [tapglue/ios_sdk#150]
I think you have forgotten to set the proper access level on the variable [`currentUser` in Tapglue.swift](https://github.com/tapglue/ios_sdk/blob/master/Sources/Tapglue.swift#L17-L21), at the moment it's internal while in [RxTapglue.swift it's set to `open`](https://github.com/tapglue/ios_sdk/blob/master/Sources/RxTapglue.swift#L19-L26) with a private setter.

Cheers.

**Comment by nilsen340** [comment]
@hellozimi thanks for the heads up, will be fixed ASAP.

**Comment by hellozimi** [comment]
@nilsen340, thanks for the quick response! Looking forward to the fix 👍

**Comment by nilsen340** [comment]
@hellozimi fixed in 2.1.1
